### ISSUE TITLE
cracktool5 的安装包或ipa能分享一个吗？

### ISSUE THREAD

**Issue by jaywhj** [Lengran1992/repo#1]
你好，cracktool5 的安装包或ipa能分享一个吗？

我看你列表有cracktool5 的汉化包，有没有原包？junewhj@qq.com，有的话，麻烦了🙏

**Comment by Lengran1992** [comment]
你好👋我汉化包均是关联官方源的，好像作者源关闭了，你可以使用搬运工源的

**Comment by jaywhj** [comment]
好的，多谢。再多请教个问题：我看搬运工源有，下载了，是一个deb包，越狱用户应该是可以直接安装了。我没越狱，只是巨魔😄，是想提取一些APP里的破解插件dylib包，我原本想的是解压deb后就能得到dylib，没想到有一些deb里不是插件，而直接是APP运行程序，直接装在deb里了，这类app 理论上，巨魔用户也能安装吧？但是需要转成ipa，这个你有经验不？有了ipa巨魔和轻松签都可以安装。发自我的 iPhone在 2024年10月30日，13:06，Lengran1992 ***@***.***> 写道：﻿
你好👋我汉化包均是关联官方源的，好像作者源关闭了，你可以使用搬运工源的

**Comment by Lengran1992** [comment]
你说的deb里是应用程序的，可以解压缩后打包ipa，再自行签名或巨魔安装。
针对TrollFools注入，我一般使用Postbox（手机端）或者Cydownload（很老的软件，支持win、mac）下载插件deb，在用huami二改的TrollFools（支持deb）直接注入。

https://github.com/borishonman/cydownload

**Comment by jaywhj** [comment]
我也是用的postbox，哈哈， cydownload还没用，抽空试试。感谢感谢👍🏻。对哦，二改的巨魔可以直接注入deb，这样就不需要打包ipa了，也可以。发自我的 iPhone在 2024年10月31日，22:29，Lengran1992 ***@***.***> 写道：﻿
你说的deb里是应用程序的，可以解压缩后打包ipa，再自行签名或巨魔安装。
针对TrollFools注入，我一般使用Postbox（手机端）或者Cydownload（很老的软件，支持win、mac）下载插件deb，在用huami二改的TrollFools（支持deb）直接注入。
https://github.com/borishonman/cydownload
